edition = "2021"

# Line length
max_width = 100

# Indentation
tab_spaces = 4
hard_tabs = false

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Functions
fn_params_layout = "Tall"
fn_call_width = 80

chain_width = 80
use_small_heuristics = "Default"

# Comments
comment_width = 100
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true

format_strings = true

struct_field_align_threshold = 0
use_field_init_shorthand = true

# Match
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

control_brace_style = "AlwaysSameLine"

# Spacing
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true

use_try_shorthand = true

reorder_modules = true

remove_nested_parens = true
overflow_delimited_expr = true
trailing_comma = "Vertical"
trailing_semicolon = true